version: "3.7"

services:
  frontend:
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: yarn dev
    volumes:
      - ./frontend:/var/www/frontend
      - frontend-tmp-data:/var/www/frontend/tmp
    tty: true
volumes:
  frontend-tmp-data:
